### ISSUE TITLE
Speed and stability information

### ISSUE THREAD

**Issue by davinellulinvega** [benureau/leabra#5]
Hello,

This is not a bug as much as a request for some more information. At the moment I am using emergent and the PBWM model for my PhD project. However, communicating from a python script to the TCP server implemented within emergent is quite slow (who am I kidding, it is very slow). Since it is used for its reinforcement learning capabilities, this means that many iterations of the same task are required for the model to learn. However, at the moment it takes a virtual agent nearly 2h to complete a task. I think you can understand where my problem lies, when I need the agent to complete at least 1000 times this task to get some significant results.
This is why I would be quite interested in building the PBWM model using this python implementation of the leabra framework. However, my concerns at this point is that this repository is still a work in progress. Therefore, I would like to know if in your opinion it would be possible to implement a stable version of the PBWM? And also to know how long it takes, for rather large networks (6 layers with at least 100 neurons each), to propagate one trial?

Thank you very much in advance for your help.
Sincerely

**Comment by rcoreilly** [comment]
The pure python version will be many times slower for any kind of larger-scale model.  We are aware of the slowness of the TCP server and are working on a fix for that — John / Kai any update on that?  Also, we are working toward a standalone C++ module that can interface with python more directly, but that will be a while away realistically.  Meanwhile, your best bet for the immediate term would probably be to get everything running directly within emergent if possible?

- Randy

**Comment by davinellulinvega** [comment]
Thank you very much for this answer.
As I mentioned in my previous post however, I do not see any way for me to keep using emergent to achieve my goals (which is unfortunate given its sophistication). Therefore, I will have to switch to another framework or maybe build a model of the basal ganglia by hand. Still I am glad to know that you are trying to expand the use cases in which emergent can be used.

Sincerely.

**Comment by apmon** [comment]
John and I (Kai) just tried to take a look at the basic speed of the server api socket, and it seemed "fairly fast". We didn't actually time it, but it looked like a response to a basic command was in the < 100ms range. (Which depending on how you use it may or may not be a speed limiting factor)

So the question might be, how exactly are you using things, and do we know where the slowness is coming from? I.e. How often are you calling commands through the server api? Is it once per cycle? once per trial, or only once per epoch or the likes? And then how much data are you passing back and forth each time? Are you creating data tables each time? Are you able to run one iteration of that purely in emergent? And how fast is this? Furthermore, is emergent running in gui mode, as that can have big performance impacts as well if the network gets displayed?

**Comment by davinellulinvega** [comment]
Hello,

Sorry for the long delay in my answer, but I was away for a few days.
For the moment I am using my emergent project for reinforcement learning. Borrowing from the Q-learning algorithm, for each step of the simulation, I have to gather the outputs for both the previous and current states and the activation of the VTA layer. After some computation and formatting in python, I send all the information back for the network to learn. Unless, I missed something in the documentation, each time I make a call to my **Activate** or **Learn** function, I first have to update the data in the input data table. Then fetch the results in the the output data table. This means that for a single call to **Activate** I have to make three requests to the server (update inputs, activate and fetch outputs). Each request taking around 200 ms to be processed (a bit more for the activation phase), when running without the GUI on an EC2 amazon instance. Therefore, from the point of view of the python script, a call to **Activate** or **Learn** takes around 600 ms. For each simulation cycle this is multiplied by 3 (which brings us to ~1.5 second) to gather all the required information and learn.
I might have been a bit quick in my first complaint. It is not the TCP server in itself that is slow. Looking at the underlying code, it could not be simpler and there is not much room for optimizing how single requests are processed. My issue was more toward the fact that to achieve one function, three requests are required. What I would expect is to be able to send the input data, together with the name of the method and have the output returned in a single request. Not sure how that would work with the current workflow imposed in emergent.
If I am allowed a bit of an unfair comparison here. I implemented a simplified version of the PBWM model with tensorflow. The total neuronal population has a size of around 500 units. Since there is no need for updating any data table and the output is directly returned, calling **Activate** or **Learn** takes on average 300 ms.

Sincerely.
